version: '2'
services:
    kmall-app:
        image: kmall
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://kmall-mysql:3306/kmall?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=kmall-elasticsearch:9300
        ports:
            - 8080:8080
    kmall-mysql:
        extends:
            file: mysql.yml
            service: kmall-mysql
    kmall-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: kmall-elasticsearch
